lab7

diff --git a/labcodes/lab5/Makefile b/labcodes/lab5/Makefile
--- a/labcodes/lab5/Makefile
+++ b/labcodes/lab5/Makefile
@@ -23,21 +23,21 @@ GCCPREFIX := $(shell if i386-elf-objdump -i 2>&1 | grep '^elf32-i386$$' >/dev/nu
 endif
 
 # try to infer the correct QEMU
-ifndef QEMU
-QEMU := $(shell if which qemu-system-i386 > /dev/null; \
-	then echo 'qemu-system-i386'; exit; \
-	elif which i386-elf-qemu > /dev/null; \
-	then echo 'i386-elf-qemu'; exit; \
-	elif which qemu > /dev/null; \
-	then echo 'qemu'; exit; \
-	else \
-	echo "***" 1>&2; \
-	echo "*** Error: Couldn't find a working QEMU executable." 1>&2; \
-	echo "*** Is the directory containing the qemu binary in your PATH" 1>&2; \
-	echo "***" 1>&2; exit 1; fi)
-endif
+#ifndef QEMU
+#QEMU := $(shell if which qemu-system-i386 > /dev/null; \
+#	then echo 'qemu-system-i386'; exit; \
+#	elif which i386-elf-qemu > /dev/null; \
+#	then echo 'i386-elf-qemu'; exit; \
+#	elif which qemu > /dev/null; \
+#	then echo 'qemu'; exit; \
+#	else \
+#	echo "***" 1>&2; \
+#	echo "*** Error: Couldn't find a working QEMU executable." 1>&2; \
+#	echo "*** Is the directory containing the qemu binary in your PATH" 1>&2; \
+#	echo "***" 1>&2; exit 1; fi)
+#endif
 
-#QEMU := /home/li/software/qemu/qemu-4.2.0/x86_64-softmmu/qemu-system-x86_64
+QEMU := /home/li/software/qemu/qemu-4.2.0/i386-softmmu/qemu-system-i386
 
 # eliminate default suffix rules
 .SUFFIXES: .c .S .h
@@ -273,7 +273,7 @@ QEMUOPTS = -hda $(UCOREIMG) -drive file=$(SWAPIMG),media=disk,cache=writeback
 qemu-mon: $(UCOREIMG) $(SWAPIMG)
 	$(V)$(QEMU)  -no-reboot -monitor stdio $(QEMUOPTS) -serial null
 qemu: $(UCOREIMG) $(SWAPIMG)
-	$(V)$(QEMU)  -no-reboot -accel tcg -parallel stdio $(QEMUOPTS) -serial null
+	$(V)$(QEMU)  -no-reboot -parallel stdio $(QEMUOPTS) -serial null
 
 qemu-nox: $(UCOREIMG) $(SWAPIMG)
 	$(V)$(QEMU)  -no-reboot -serial mon:stdio $(QEMUOPTS) -nographic
@@ -314,7 +314,7 @@ MAKEOPTS		:= --quiet --no-print-directory
 
 grade:
 	$(V)$(MAKE) $(MAKEOPTS) clean
-	$(V)$(SH) tools/grade.sh > /home/li/software/Memtime
+	$(V)$(SH) tools/grade.sh
 
 touch:
 	$(V)$(foreach f,$(TOUCH_FILES),$(TOUCH) $(f))
